print("Create your character!")
gender = input("What gender is your character?")
name = input("What is your character called?")
age=input("How old is your character?")
strengths = input("What are your character's srengths?")
weaknesses=input("What are your character's weaknesses?")
print("Your character's name is", name)
print("Your character is a", gender)
print("Your character is", age, "years old")
print("Srengths:", strengths)
print("Weaknesses:", weaknesses)
print(name, "says, 'Thank you for creating me(you transgender gay person)!'")
